sonar.projectKey=mytelkomsel-web-prepaid-registration
sonar.qualitygate.wait=true
sonar.sources=.
sonar.exclusions=**/node_modules/**,Dockerfile,src/routes/**,nginx/**,**/translation/**,src/infrastructure/**,src/@core/protocols/**,src/assets/**,src/routeTree.gen.ts,**/*.config.{js,jsx,ts,tsx,cjs,mjs},i18nConfig.ts
sonar.sourceEncoding=UTF-8
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/*.config.ts,**/*.config.js,**/*.config.cjs,**/*.setup.ts,src/main.tsx,**/translation/**,**/__mocks__/**
