/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathlessLayoutLandingPageRouteImport } from './routes/_pathlessLayout/landing-page'
import { Route as PathlessLayoutAboutRouteImport } from './routes/_pathlessLayout/about'

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutLandingPageRoute =
  PathlessLayoutLandingPageRouteImport.update({
    id: '/landing-page',
    path: '/landing-page',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutAboutRoute = PathlessLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PathlessLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof PathlessLayoutAboutRoute
  '/landing-page': typeof PathlessLayoutLandingPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof PathlessLayoutAboutRoute
  '/landing-page': typeof PathlessLayoutLandingPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/_pathlessLayout/about': typeof PathlessLayoutAboutRoute
  '/_pathlessLayout/landing-page': typeof PathlessLayoutLandingPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/landing-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/landing-page'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/_pathlessLayout/about'
    | '/_pathlessLayout/landing-page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/landing-page': {
      id: '/_pathlessLayout/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof PathlessLayoutLandingPageRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/about': {
      id: '/_pathlessLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PathlessLayoutAboutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutAboutRoute: typeof PathlessLayoutAboutRoute
  PathlessLayoutLandingPageRoute: typeof PathlessLayoutLandingPageRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutAboutRoute: PathlessLayoutAboutRoute,
  PathlessLayoutLandingPageRoute: PathlessLayoutLandingPageRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
